blueprint: "3.0.0 (AI-Native)"
#----------------------------------------------------------
# このBDA は必要最小のベースラインを採用しています。
#----------------------------------------------------------

# =========================================================
# META & GUIDELINES
# AIへの技術スタックと実装ルールの指示
# =========================================================
meta:
  appName: "NextFastTodo"
  version: "0.1.0"

guidelines:
  backend:
    framework: "FastAPI (Python)"
    db: "SQLite (with SQLAlchemy)"
    auth: "OAuth2 with JWT (python-jose)"
    validation: "Pydantic v2"
    style: "PEP8, Type Hints必須"
  
  frontend:
    framework: "Next.js 14+ (App Router)"
    language: "TypeScript"
    styling: "Tailwind CSS"
    state: "React Hooks (Context API or Zustand)"
    apiClient: "Axios (generates types from backend schemas)"
    style: "Functional Components, Prettier"

# =========================================================
# 1. DOMAIN (Shared Data Schemas)
# =========================================================
domain:
  schemas:
    - name: User
      properties:
        - { name: id, type: Integer }
        - { name: email, type: String }
        - { name: is_active, type: Boolean }

    - name: UserCreate
      properties:
        - { name: email, type: String }
        - { name: password, type: String }

    - name: Token
      properties:
        - { name: access_token, type: String }
        - { name: token_type, type: String }

    - name: TodoItem
      properties:
        - { name: id, type: Integer }
        - { name: title, type: String }
        - { name: description, type: String? }
        - { name: completed, type: Boolean }
        - { name: user_id, type: Integer }

# =========================================================
# 2. API DEFINITION (Contract)
# Backend実装とFrontendクライアントの仕様
# =========================================================
api:
  endpoints:
    - name: Auth
      base: "/auth"
      operations:
        - { method: POST, path: "/token", input: UserCreate, output: Token, desc: "Login to get JWT" }
        - { method: POST, path: "/register", input: UserCreate, output: User, desc: "Create new user" }
    
    - name: Todos
      base: "/todos"
      operations:
        - { method: GET, path: "/", output: "List<TodoItem>", desc: "Get my todos" }
        - { method: POST, path: "/", input: TodoItem, output: TodoItem, desc: "Create todo" }
        - { method: PUT, path: "/{id}", input: TodoItem, output: TodoItem, desc: "Update todo" }
        - { method: DELETE, path: "/{id}", output: Boolean, desc: "Delete todo" }

# =========================================================
# 3. FRONTEND FEATURES (UI/UX Specs)
# =========================================================
features:
  # --- Login Screen ---
  - id: LoginFeature
    name: LoginPage
    path: "/login"
    
    state:
      - { name: email, type: String, default: "" }
      - { name: password, type: String, default: "" }
      - { name: isLoading, type: Boolean, default: false }
      - { name: error, type: String?, default: null }

    inputs:
      - { name: onEmailChange, args: [{name: val, type: String}] }
      - { name: onPasswordChange, args: [{name: val, type: String}] }
      - { name: onSubmit, args: [] }
      - { name: onRegisterClick, args: [] }

    scenarios:
      # 表示状態テスト
      - name: "Initial View"
        given:
          state: { email: "", password: "", isLoading: false, error: null }

      - name: "Loading State"
        given:
          state: { email: "test@example.com", isLoading: true }

      - name: "Login Error"
        given:
          state: { error: "Invalid credentials" }

      # 操作テスト：空フォームで送信
      - name: "Submit Empty Form"
        given:
          state: { email: "", password: "" }
        when:
          - { input: onSubmit }
        then:
          state: { error: "Email is required" }

      # 操作テスト：正常ログイン開始
      - name: "Submit Valid Form"
        given:
          state: { email: "test@example.com", password: "password123" }
        when:
          - { input: onSubmit }
        then:
          state: { isLoading: true }

  # --- Todo Dashboard ---
  - id: TodoListFeature
    name: TodoPage
    path: "/dashboard"
    
    state:
      - { name: todos, type: "List<TodoItem>", default: [] }
      - { name: filter, type: "Enum[All, Active, Completed]", default: All }

    inputs:
      - { name: onAddTodo, args: [{name: title, type: String}] }
      - { name: onToggleTodo, args: [{name: id, type: Integer}] }
      - { name: onDeleteTodo, args: [{name: id, type: Integer}] }
      - { name: onLogout, args: [] }
    
    scenarios:
      - name: "Empty Todo List"
        given:
          state: { todos: [], filter: All }
      
      - name: "Add Todo"
        given:
          state: { todos: [] }
        when:
          - { input: onAddTodo, args: { title: "Buy milk" } }
        then:
          state: { todos: [{ title: "Buy milk", completed: false }] }

# =========================================================
# 4. ROUTING
# =========================================================
routing:
  entry: /login
  structure:
    - name: RootLayout
      children:
        - { name: Login, feature: LoginFeature }
        - { name: Dashboard, feature: TodoListFeature, guard: AuthGuard }